### ISSUE TITLE
SAFT EOS example not executing as intented 

### ISSUE THREAD

**Issue by ECFE** [ypaul21/Clapeyron.jl#112]
The provided ipyb example for the SAFT EOS seems to have some issues: 

Specifically getting the critical points seems to produce a domain error (command: crit = crit_pure.(models); for the associated domain error see the attached file. 

[julia-ipyb-error.txt](https://github.com/ypaul21/Clapeyron.jl/files/9447144/julia-ipyb-error.txt)

**Comment by pw0908** [comment]
Thank you for pointing this out; this is a problem with our CPA equation of state that re-appears every now and again where the solvers predict a negative temperature for some reason. We've tried to modify the initial guesses for the critical point in CPA but there always seems to be issues. I'll take another look to see if we can generalise this better.

We should probably check if all the notebooks still work as intended as well.
