### ISSUE TITLE
multi-component_vle_vlle_lle_crit issue

### ISSUE THREAD

**Issue by branch171** [ypaul21/Clapeyron.jl#113]
A number of example notebooks have erros and do not execute:

The notebook multi-component_vle_vlle_lle_crit has an error as follows:

MethodError: no method matching ChemPotBubblePressure

Also the SAFT_eos.ipynb has a domain error for the CPA equation of state.

Any help in how to fix these.

**Comment by pw0908** [comment]
Hi there!

Thanks for pointing this out! I've spent the morning fixing the notebooks / codes. If you use the latest version of Clapeyron and the notebooks, they should all work except the tp_flash one which needs a complete overhaul.

Feel free to let us know if you experience any further issues.
