### ISSUE TITLE
speed of Calpeyron

### ISSUE THREAD

**Issue by branch171** [ypaul21/Clapeyron.jl#122]
Hi, I am using Calpeyron and have it working. However, even for a simple model with 2 components CO2 and N2 if I do a bubble point calculation it takes an enormous amount of time to get an answer. In fact, just setting the model takes ages.

I am doing this from the REPL. Is there a way to speed things up or is this as good as it is.

My session is:

using Pkg
using Clapeyron
model = GERG2008(["carbon dioxide","nitrogen"]);
z=[0.996,0.004];
bubble_temperature(model,40e5,z)

I am doing this from the REPL. Is there a way to speed things up or is this as good as it is.

Thanks

**Comment by branch171** [comment]
here are the timings:

julia> using Clapeyron

julia> @time model = GERG2008(["carbon dioxide","nitrogen"])
  2.106798 seconds (5.45 M allocations: 284.842 MiB, 2.71% gc time, 99.96% compilation time)
GERG2008 with 2 components:
 "carbon dioxide"
 "nitrogen"

julia> z=[0.996,0.004]
2-element Vector{Float64}:
 0.996
 0.004

julia> @time bubble_temperature(model, 40e5,z)
 29.439166 seconds (85.80 M allocations: 4.253 GiB, 4.18% gc time, 99.92% compilation time)
(276.4968315845077, 4.866631958200414e-5, 0.00038309691825400265, [0.9675012746913377, 0.03249872530866227])

We can see it takes 2 seconds the instantiate the model and 30 seconds to solve a simple binary bubble point problem.

**Comment by branch171** [comment]
Ok I see the issue it's that we have to call the function once in a REPL or other session, for the function to be compiled. After that the compilation is not needed for that function and the function call is very fast. it goes from 30 seconds to 1 millisec.

**Comment by longemen3000** [comment]
Hi!

A long term goal is to have this package completely compiled, but it needs work on the julia side for now, for an easy distribution of binaries (fortunately they move fast!). This is widely known in the Julia community as TTFP (Time to first plot, or in this case, Time to first phase eq). At the moment, the best way to use Clapeyron is within an open julia session, notebook, or REPL. I know there is a way to compile the package, by compiling it along a system image, via https://github.com/JuliaLang/PackageCompiler.jl , but personally i've never tried it

**Comment by branch171** [comment]
Hi Thanks very much for the feedback. I can confirm that PackageCompiler works, you end up with a sys-image that you can load on start up of Julia. If you define a simple function that includes calls to all the functions you want to use from your sys-image then you get your functions precompiled in your sys-image and from then on they will load and run fast in your julia session. The more functions you add to your function the slower that precompile is but from then on you have the fast function access. 

As I understand the sys-image so or dll you produce can only be used in Julia. If you want to use the so or dll from another language need to wrap the function with the Base.@ccallable macro, this I have not yet tested but there are good examples.
