### ISSUE TITLE
Example for SAFT-VRQ

### ISSUE THREAD

**Issue by ianhbell** [ypaul21/Clapeyron.jl#127]
I'd like to calculate parameters with the SAFT-VRQ model, but I am not sure how to instantiate this model.  Can you provide an example? I thought I remembered seeing an example somewhere, but I went all through the docs and folder of examples and didn't find it.

**Comment by pw0908** [comment]
Hi Ian, that EoS goes under the name SAFT-VRQ Mie in our code and you can find details on it in our documentation: 

https://ypaul21.github.io/Clapeyron.jl/dev/eos/saft/#Clapeyron.SAFTVRQMie

I'll add the slight caveat that this is the second order version of SAFT-VRQ Mie. We probably should try to support the first order version as well.

**Comment by pw0908** [comment]
Should be the same as everything else:

```julia
using Clapeyron

model = SAFTVRQMie(["helium"])

sat = saturation_pressure(model, 2.5)
```

**Comment by ianhbell** [comment]
Ah, very simple, an example like that would be nice to provide in the docs.
