### ISSUE TITLE
HELP - not an issue

### ISSUE THREAD

**Issue by SalvadorBrandolin** [ypaul21/Clapeyron.jl#138]
Hi! I'm trying to define a new alpha function (Mathias Copeman). I'm a Julia noob, so I followed the Clapeyron documentation tutorial and couldn't find what's wrong.

my mathiascopeman.jl file

```Julia
using Clapeyron

abstract type MathiasCopemanAlphaModel <: AlphaModel end

struct MathiasCopemanAlphaParam <: EoSParam
    c1::SingleParam{Float64}
    c2::SingleParam{Float64}
    c3::SingleParam{Float64}
end

@newmodelsimple MathiasCopemanAlpha MathiasCopemanAlphaModel MathiasCopemanAlphaParam
export MathiasCopemanAlpha

MathiasCopemanAlpha

function MathiasCopemanAlpha(components::Vector{String}; userlocations::Vector{String}=String[], verbose::Bool=false)
    params = getparams(components; userlocations=userlocations, verbose=verbose)
    c1 = params["c1"]
    c2 = params["c2"]
    c3 = params["c3"]
    packagedparams = MathiasCopemanAlphaParam(c1,c2,c3)
    model = MathiasCopemanAlpha(packagedparams, verbose=verbose)
    return model
end

function α_function(model::CubicModel,V,T,z,alpha_model::MathiasCopemanAlphaModel)
    Tc = model.params.Tc.values
    _c1  = alpha_model.params.c1.values
    _c2  = alpha_model.params.c2.values
    _c3  = alpha_model.params.c3.values
    α = zeros(typeof(T*1.0),length(Tc))
    for i in Clapeyron.@comps
        c1 = _c1[i]
        c2 = _c2[i]
        c3 = _c3[i]
        Tr = T/Tc[i]
        α[i] = (1 + c1 * (1 - (Tr)^0.5) + c2 * (1 - (Tr)^0.5)^2 + c3 * (1 - (Tr)^0.5)^3)^2
    end
    return α
end

function α_function(model::CubicModel,V,T,z::Clapeyron.SingleComp,alpha_model::MathiasCopemanAlphaModel)
    Tc = model.params.Tc.values[1]
    c1  = alpha_model.params.c1.values[1]
    c2  = alpha_model.params.c2.values[1]
    c3  = alpha_model.params.c3.values[1]
    Tr = T/Tc
    α = (1 + c1 * (1 - (Tr)^0.5) + c2 * (1 - (Tr)^0.5)^2 + c3 * (1 - (Tr)^0.5)^3)^2
end
```

Then... in another file trying to use the alpha model:

```Julia
using Clapeyron

include("mathiascopeman.jl")

model = PR(["water"], alpha=MathiasCopemanAlpha, alpha_userlocations=["database/"])

volume(model, 101325, 303.15)
```

I get:
MethodError: no method matching α_function(::PR{BasicIdeal, MathiasCopemanAlpha, NoTranslation, vdW1fRule}, ::Int64, ::Float64, ::StaticArraysCore.SVector{1, Float64}, ::MathiasCopemanAlpha)
Closest candidates are:
  α_function(::Clapeyron.PRModel, ::Any, ::Any, ::Any, ::Clapeyron.BMAlphaModel) at ~/.julia/packages/Clapeyron/wx1tK/src/models/cubic/alphas/BM.jl:70
  α_function(::CubicModel, ::Any, ::Any, ::Any, ::Clapeyron.PR78AlphaModel) at ~/.julia/packages/Clapeyron/wx1tK/src/models/cubic/alphas/PR78Alpha.jl:47
  α_function(::CubicModel, ::Any, ::Any, ::Any, ::Clapeyron.CPAAlphaModel) at ~/.julia/packages/Clapeyron/wx1tK/src/models/cubic/alphas/CPAAlpha.jl:40
  ...

Stacktrace:
  [1] macro expansion
    @ ~/.julia/packages/Clapeyron/wx1tK/src/utils/macros.jl:77 [inlined]
  [2] cubic_ab(model::PR{BasicIdeal, MathiasCopemanAlpha, NoTranslation, vdW1fRule}, V::Int64, T::Float64, z::StaticArraysCore.SVector{1, Float64}, n::Float64)
    @ Clapeyron ~/.julia/packages/Clapeyron/wx1tK/src/models/cubic/equations.jl:53
  [3] cubic_ab(model::PR{BasicIdeal, MathiasCopemanAlpha, NoTranslation, vdW1fRule}, V::Int64, T::Float64, z::StaticArraysCore.SVector{1, Float64})
    @ Clapeyron ~/.julia/packages/Clapeyron/wx1tK/src/models/cubic/equations.jl:50
  [4] cubic_poly(model::PR{BasicIdeal, MathiasCopemanAlpha, NoTranslation, vdW1fRule}, p::Int64, T::Float64, z::StaticArraysCore.SVector{1, Float64})
    @ Clapeyron ~/.julia/packages/Clapeyron/wx1tK/src/models/cubic/equations.jl:90
  [5] volume_impl(model::PR{BasicIdeal, MathiasCopemanAlpha, NoTranslation, vdW1fRule}, p::Int64, T::Float64, z::StaticArraysCore.SVector{1, Float64}, phase::Symbol, threaded::Bool, vol0::Nothing)
    @ Clapeyron ~/.julia/packages/Clapeyron/wx1tK/src/models/cubic/equations.jl:189
  [6] volume(model::PR{BasicIdeal, MathiasCopemanAlpha, NoTranslation, vdW1fRule}, p::Int64, T::Float64, z::StaticArraysCore.SVector{1, Float64}; phase::Symbol, threaded::Bool, vol0::Nothing)
    @ Clapeyron ~/.julia/packages/Clapeyron/wx1tK/src/methods/property_solvers/volume.jl:105
  [7] volume(model::PR{BasicIdeal, MathiasCopemanAlpha, NoTranslation, vdW1fRule}, p::Int64, T::Float64, z::StaticArraysCore.SVector{1, Float64}) (repeats 2 times)
    @ Clapeyron ~/.julia/packages/Clapeyron/wx1tK/src/methods/property_solvers/volume.jl:104
  [8] top-level scope
    @ In[63]:3
  [9] eval
    @ ./boot.jl:368 [inlined]
 [10] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1428

If it helps, I've tried:
```Julia
model = PR(["water"], alpha=MathiasCopemanAlpha, alpha_userlocations=["database/"])
model2 = MathiasCopemanAlpha(["water"], userlocations=["database/"])
α_function(model, nothing, 303.15, [1], model2)
```
And it works:
1-element Vector{Float64}:
 1.68833512624511

The alpha value for water is correct...

Sorry for bothering and thank you in advance.

**Comment by longemen3000** [comment]
Hi!
This is more of a Julia idiom than a Clapeyron specific issue. when you define a new function in julia, the function and it's methods are attached to the module that are defined. for example:
```
julia> α_function(a::Int,b,c) = zeros(a)
α_function (generic function with 1 method)

julia> Clapeyron.α_function
α_function (generic function with 19 methods)
```
if you see, `Clapeyron.α_function` is a function with the name `α_function` attached to the module `Clapeyron`. whereas the first one is attached to the REPL instance (`Main` Module) :
```
julia> Main.α_function
α_function (generic function with 1 method)
```
there are two solutions for this:
1- define the method with `Clapeyron` preceding it:
```
function Clapeyron.α_function(model::CubicModel,V,T,z::Clapeyron.SingleComp,alpha_model::MathiasCopemanAlphaModel)
```
2- import the method you want to overload at the start:
```
import Clapeyron: α_function #now you "brought" α_function to your local scope (in this case the REPL) so you can add new methods.
```

**Comment by SalvadorBrandolin** [comment]
OMG thank you! And sorry for the Julia noob mistake.

**Comment by longemen3000** [comment]
no prob, if anything, we should add that to our docs too
