### ISSUE TITLE
Inaccurate property methods

### ISSUE THREAD

**Issue by stillyslalom** [ypaul21/Clapeyron.jl#25]
As a basic correctness check, I queried the speed of sound and isentropic exponent of nitrogen at STP using Peng-Robinson and PC-SAFT models.
```
julia> using Clapeyron, Unitful

julia> N2_PR = PR(["nitrogen"])
PR{BasicIdeal} with 1 component:
 "nitrogen"
Contains parameters: a, b, acentricfactor, Tc, Pc, Mw

julia> N2_SAFT = PCSAFT(["nitrogen"])
PCSAFT{BasicIdeal} with 1 component:
 "nitrogen"
Contains parameters: Mw, segment, sigma, epsilon, epsilon_assoc, bondvol

julia> speed_of_sound(N2_PR, 101325u"Pa", 300u"K")
8669.296616665222 m s^-1

julia> speed_of_sound(N2_SAFT, 101325u"Pa", 300u"K")
10468.079131748613 m s^-1

julia> isobaric_heat_capacity(N2_PR, 101325u"Pa", 300u"K") / isochoric_heat_capacity(N2_PR, 101325u"Pa", 300u"K")
874.8616410752167

julia> isobaric_heat_capacity(N2_SAFT, 101325u"Pa", 300u"K") / isochoric_heat_capacity(N2_SAFT, 101325u"Pa", 300u"K")
1275.2917204657658
```
Needless to say, these values are a bit off the mark (a = 352 m/s and γ=1.4). The test suite has [some property tests](https://docs.julialang.org/en/v1/stdlib/Test/#Broken-Tests), but relative tolerances are set to `1E10`. If this functionality is not yet implemented (/validated), I would recommend changing that test block to [`@test_skip`](https://docs.julialang.org/en/v1/stdlib/Test/#Broken-Tests) and clarifying the current state of property methods in the documentation.

**Comment by pw0908** [comment]
Hi Alex,

This is on us for not being clearer in the documentation. By setting up the models in this way, you've used the default ideal model which we call "BasicIdeal". This only carries a volume and composition dependence, no temperature dependence. This makes properties that depend on the first and second order temperature derivatives unusable. 

Fixing this is relatively straight-forward, you can use the WalkerIdeal model since it has the parameters you need:
```julia
julia> using Clapeyron, Unitful

julia> N2_PR = PR(["nitrogen"];idealmodel=WalkerIdeal)
PR{WalkerIdeal} with 1 component:
 "nitrogen"
Contains parameters: a, b, acentricfactor, Tc, Pc, Mw

julia> N2_SAFT = PCSAFT(["nitrogen"];idealmodel=WalkerIdeal)
PCSAFT{WalkerIdeal} with 1 component:
 "nitrogen"
Contains parameters: Mw, segment, sigma, epsilon, epsilon_assoc, bondvol

julia> speed_of_sound(N2_PR, 101325u"Pa", 300u"K")
347.00051443031396 m s⁻¹

julia> speed_of_sound(N2_SAFT, 101325u"Pa", 300u"K")
347.0215687936945 m s⁻¹

julia> isobaric_heat_capacity(N2_PR, 101325u"Pa", 300u"K") / isochoric_heat_capacity(N2_PR, 101325u"Pa", 300u"K")
1.4016251686654189

julia> isobaric_heat_capacity(N2_SAFT, 101325u"Pa", 300u"K") / isochoric_heat_capacity(N2_SAFT, 101325u"Pa", 300u"K")
1.4014850964933816```

The next area of focus for us is indeed the tests (and refining the docs); thank you for pointing this out!

**Comment by pw0908** [comment]
I've now added a very basic fix to the BasicIdeal model where it now includes the translational motions of the species; it's still not quantitatively accurate, but it will give more-reasonable values for these second derivative properties.

**Comment by stillyslalom** [comment]
Thanks, those values are now within 10-20% with `BasicIdeal`.

**Comment by pw0908** [comment]
Yes, it's not meant to be quantitatively accurate since nitrogen has rotational and vibrational modes not accounted for in the BasicIdeal model.
