### ISSUE TITLE
VLE/VLLLE

### ISSUE THREAD

**Issue by ianhbell** [ypaul21/Clapeyron.jl#67]
FYI: The paper about the algorithm for finding VLLE from VLE tracing is now published: https://pubs.acs.org/doi/10.1021/acs.iecr.1c04703 .  Let me know if you have any questions.

**Comment by pw0908** [comment]
Thanks! Looking forward to reading it!

**Comment by pw0908** [comment]
Actually, if you're interested in implementing these tracing schemes, Julia has an amazing differential equations library (DifferentialEquations.jl). I created a rudimentary version of the basic bubble pressure tracing scheme and it seems that your approach is three times faster than just using our default bubble pressure solver

**Comment by ianhbell** [comment]
You mean to trace from the pure fluid to the composition of interest? I'm not too surprised, the approach is very nice, and even more importantly, very reliable.
