### ISSUE TITLE
E-PPR78

### ISSUE THREAD

**Issue by pw0908** [ypaul21/Clapeyron.jl#78]
An impressive EoS: https://www.sciencedirect.com/science/article/pii/S0378381222000814

Aside from the GC component, I think we should be able to implement it very easily.

**Comment by longemen3000** [comment]
`Akl` and `Bkl` are in table s4 of the suplementary information. if i understand correctly this can be implemented by doing something like:
```
PR(components, mixing = HVRule, activity = EPPR78Activity)
```

**Comment by pw0908** [comment]
Oh yea, should be quite easy

**Comment by pw0908** [comment]
We should probably implement regular PPR78 anyways
