### ISSUE TITLE
Volume solver stability check bypassed

### ISSUE THREAD

**Issue by lucpaoli** [ypaul21/Clapeyron.jl#96]
In the volume solver, should all be operating normally (under critical point, two volume roots found etc), the gibbs free energies of the phases are checked, and the phase that minimises gibbs is returned:
```julia
    if gg<gl
        isstable(model,Vg,T,z,phase)
        return Vg
    else
        isstable(model, Vl, T, z, phase)
        return Vl
    end
```

However, by passing the phase to the stability check ``isstable``, the isstable function automatically returns ``true``
```julia
function isstable(model, V, T, z, phase=:stable)
    if phase != :stable
        return true
...etc
```

This doesn't seem like the intended use of the stability check, is this how it's intended to be used?

**Comment by longemen3000** [comment]
the default volume solver only performs mechanical stability (it is done in `volume_compress`. but this kw should be open to the api
